services:
  db:
    image: postgres:16
    container_name: social_media_sentiments
    environment:
      POSTGRES_DB: realtime_social_media_sentiments
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/home/postgres/pgdata/data
    networks:
      - realtime-social-media-sentiments-net
    restart: unless-stopped

  broker:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,EXTERNAL://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:29092"
    networks:
      - realtime-social-media-sentiments-net

  spark-master:
    image: apache/spark:3.5.1
    container_name: spark-master
    hostname: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master -h 0.0.0.0
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_LOCAL_IP=0.0.0.0
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040-4050:4040-4050"
    networks:
      - realtime-social-media-sentiments-net
    volumes:
      - ./data:/opt/spark/work-dir/data

  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    networks:
      - realtime-social-media-sentiments-net
    volumes:
      - ./data:/opt/spark/work-dir/data

  spark-training:
    build:
      context: ./spark/training
      dockerfile: DOCKERFILE
    container_name: spark-training
    depends_on:
      - spark-master
      - spark-worker
      - broker
    networks:
      - realtime-social-media-sentiments-net
    volumes:
      - ./data:/opt/spark/work-dir/data

  spark-streaming:
    build:
      context: ./spark/streaming
      dockerfile: DOCKERFILE
    container_name: spark-streaming
    depends_on:
      - spark-master
      - spark-worker
      - spark-training
      - broker
    networks:
      - realtime-social-media-sentiments-net
    volumes:
      - ./data:/opt/spark/work-dir/data
    # restart: on-failure

networks:
  realtime-social-media-sentiments-net:
    driver: bridge

volumes:
  pg_data: